[membership]
title = "V LIVE ─ STORE ─ MEMBERSHIP"
url = "https://www.vlive.tv/vstore/membership?lang=ko"
entrySelector = "ul.channel_fanship_list._mem_list li"
titleSelector = "strong.title"
linkSelector = "a.store_fanship_card"
contentSelector = "em.icon_fanship"
imageSelector = "div.thumb_area img"
waitUntil = "networkidle"

[video]
title = "V LIVE ─ STORE ─ V LIVE+"
url = "https://www.vlive.tv/vstore/video?lang=ko"
entrySelector = "ul.best_package_list li"
titleSelector = "strong.info_tit"
linkSelector = "a.store_package_card"
contentSelector = "div.info_date span.date"
imageSelector = "div.thumb_area img"
waitUntil = "networkidle"

[lightstick]
title = "V LIVE ─ STORE ─ LIGHTSTICK"
url = "https://www.vlive.tv/vstore/lightStick"
entrySelector = "ul.store_lightstick_list li"
titleSelector = "div.text_area strong.title"
linkSelector = "a.lightstick_link"
contentSelector = "div.text_area div.text"
imageSelector = "div.img_area img"
waitUntil = "networkidle"

[sticker]
title = "V LIVE ─ STORE ─ STICKER"
url = "https://www.vlive.tv/vstore/sticker"
entrySelector = "ul.store_sticker_list li"
titleSelector = "div.tit_area p.tit"
linkSelector = "a.sticker_link"
contentSelector = "div.sticker_info a.info_channel"
imageSelector = "div.thumb_area img"
waitUntil = "networkidle"
